### ISSUE TITLE
Get total rows

### ISSUE THREAD

**Issue by RodolfoSilva** [bhoriuchi/bookshelf-pagemaker#5]
How can I get the total rows?

``` javascript
var pm = require('bookshelf-pagemaker')(bookshelf);

var User = bookshelf.Model.extend({
  tableName: 'users'
});

pm(User).forge()
  .limit(2)
  .page(2)
  .paginate()
  .end()
  .then(function(results) {
    console.log(results.total);
  });
```

**Comment by RodolfoSilva** [comment]
I have found one solution for this.

``` javascript
var pm = require('bookshelf-pagemaker')(bookshelf);

var User = bookshelf.Model.extend({
  tableName: 'users'
});

pm(User, 'offset').forge()
  .limit(2)
  .page(2)
  .paginate()
  .end()
  .then(function(results) {
    console.log(results.resourcesTotal);
  });
```

**Comment by bhoriuchi** [comment]
Pagination are customizable by passing a pagination configuration to the module. See https://github.com/bhoriuchi/bookshelf-pagemaker/wiki/Pagination-Configuration

However if you like one of the canned configurations like paged but just want to hide or show some of the configuration i will add an option to the pagination method to do this so that you don't need to produce an entire config and can build off an existing one
